---
vms:
  - name: pfsense_2.7.2
    dns_name: pfsense272
    vmid: 100
    cpu: 1
    memory: 512
    disk_size: 8
    os_type: other
    networks:
      - bridge: vmbr01
      - bridge: vmbr02
      - bridge: vmbr10
      - bridge: vmbr20
      - bridge: vmbr30
    isos: 
      - pfSense-CE-2.7.2-RELEASE-amd64.iso
      - configs.iso
    bootorder: ide2;scsi0
  - name: k8sdev
    dns_name: k8sdev
    vmid: 101
    cpu: 2
    memory: 2048
    disk_size: 8
    os_type: l26
    networks:
      - bridge: vmbr10
    isos: 
      - cloud-init
    imgs: 
      - noble-server-cloudimg-amd64.img
    bootorder: scsi0
  - name: k8suat
    dns_name: k8suat
    vmid: 102
    cpu: 2
    memory: 2048
    disk_size: 8
    os_type: l26
    networks:
      - bridge: vmbr10
    isos: 
      - cloud-init
    imgs: 
      - noble-server-cloudimg-amd64.img
    bootorder: scsi0
  - name: k8sprod
    dns_name: k8sprod
    vmid: 103
    cpu: 2
    memory: 2048
    disk_size: 8
    os_type: l26
    networks:
      - bridge: vmbr10
    isos: 
      - cloud-init
    imgs: 
      - noble-server-cloudimg-amd64.img
    bootorder: scsi0