---
ansible_user: "{{ lookup('env', 'PM_USER') }}"
ansible_password: "{{ lookup('env', 'PM_PASSWORD') }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}"
proxmox_user: "{{ lookup('env', 'PM_USER') }}"
proxmox_password: "{{ lookup('env', 'PM_PASSWORD') }}"
proxmox_host: "{{ lookup('env', 'PM_ADDRESS') }}"
proxmox_node: pve