---
- name: Configure Proxmox Network
  hosts: proxmox
  gather_facts: true
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/devops/github/homelab/IaC/ansible/inventory/group_vars/proxmox_network.yaml"
  tasks:
    - name: Create network bridges using pvesh
      ansible.builtin.command:
        cmd: >
          pvesh create /nodes/{{ proxmox_node }}/network
          -type bridge
          -iface {{ item.name }}
          {% if item.bridge_ports is defined %}
          -bridge_ports {{ item.bridge_ports }}
          {% endif %}
          {% if item.autostart is defined %}
          -autostart {{ item.autostart }}
          {% endif %}
      loop: "{{ bridges }}"
      loop_control:
        loop_var: item

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Wait for the server to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Ensure the server is fully up and running
      ansible.builtin.command:
        cmd: uptime
      register: uptime_result
      until: uptime_result.rc == 0
      retries: 5
      delay: 10