---
- name: Setup Proxmox Users
  hosts: proxmox
  gather_facts: false
  vars_files:
    - "{{ lookup('env', 'HOME') }}/devops/github/homelab/IaC/ansible/inventory/group_vars/proxmox_users.yaml"
  tasks:
    - name: Create Proxmox users
      community.general.proxmox_user:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_validate_certs: no
        user: "{{ item.username }}"
        password: "{{ item.password }}"
        role: "{{ item.role }}"
      loop: "{{ proxmox_users }}"
      become: yes