---
- name: Create configuration files on Proxmox Host
  hosts: proxmox
  gather_facts: true
  become: yes
  vars_files:
    - "{{ lookup('env', 'HOME') }}/devops/github/homelab/IaC/ansible/inventory/group_vars/proxmox_configs.yaml"
  tasks:
    - name: Ensure configuration directory exists
      ansible.builtin.file:
        path: /tmp/configs
        state: directory
        mode: '0755'

    - name: Clear existing configuration files
      ansible.builtin.shell: |
        rm -Rf /tmp/configs/* && \
        rm -Rf /var/lib/vz/template/iso/configs.iso

    - name: Create configuration files
      ansible.builtin.template:
        src: "{{ item.file }}"
        dest: "/tmp/configs/{{ item.name }}configs.xml"
      loop: "{{ configs }}"
      loop_control:
        loop_var: item
      vars:
        DOMAIN: "{{ lookup('env', 'DOMAIN') }}"
        NETWORK: "{{ lookup('env', 'NETWORK') }}"
        BCRYPT_HASH: "{{ lookup('env', 'BCRYPT_HASH')  }}"

    - name: Create ISO image with configuration files
      ansible.builtin.shell: |
        genisoimage -o /var/lib/vz/template/iso/configs.iso $(find /tmp/configs -name '*configs.xml')
      args:
        creates: /var/lib/vz/template/iso/configs.iso