---
- name: Update Proxmox Host
  hosts: proxmox
  gather_facts: true
  become: yes
  tasks:
    - name: Replace Proxmox Enterprise repository with Community repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

    - name: Remove Proxmox Enterprise repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    - name: Clean up unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
        autoclean: yes

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Wait for the server to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Ensure the server is fully up and running
      ansible.builtin.command:
        cmd: uptime
      register: uptime_result
      until: uptime_result.rc == 0
      retries: 5
      delay: 10